apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense 
  labels:
    component: mysql
    tier: db
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      component: mysql
      tier: db
      project: expense
  template:
    metadata:
      labels:
        component: mysql
        tier: db
        project: expense
    spec:
      containers:
      - name: mysql
        image: joindevops/mysql:v1.0

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec: 
  selector:
    tier: db
    project: expense
    component: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306